/**
 * Pastebin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject1 { 
    /**
     * 
     */
    doctor: string;
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    date: string;
    /**
     * 
     */
    controlDate: string;
    /**
     * 
     */
    patient: string;
}
